### ISSUE TITLE
App Crashing 

### ISSUE THREAD

**Issue by cgarrett** [GeorgeCiesinski/text-script#36] opened 2020-02-27 22:02 UTC
The app seems to crash nearly every time I try to run a textblock. I've set up 8 so far and for the first day, they seemed to run as expected in our ticketing system and Gmail. Now the program seems to crash every time I try to run one, but it doesn't seem to consistently log errors. The one below is the only error I've actually seen logged and it was from yesterday. I've crashed the program several times today, but it's not logging. The texblock files were all created in Sublime Text as regular text files, named in accordance with the ReadMe file. I've tried opening and saving them in Notepad with the same result. I also tried moving them into subdirectories to help organize, which again, seemed to work for a day, but later after running the app again, it seemed to have issues so I moved them all back to the Textblocks root.

From the logs.log.3 file:
2020-02-26 16:06:46,629 - DEBUG : Successfully found the textblock directory: ./textblocks/urls\#bansecrprod.txt
2020-02-26 16:06:46,631 - ERROR : Attempted to open file in UTF-16. Unsuccessful.
Traceback (most recent call last):
  File "TextController.py", line 295, in _read_textblock
  File "c:\users\gciesinski\appdata\local\programs\python\python37\lib\codecs.py", line 322, in decode
  File "c:\users\gciesinski\appdata\local\programs\python\python37\lib\encodings\utf_16.py", line 61, in _buffer_decode
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2f in position 50: truncated data
2020-02-26 16:06:46,632 - DEBUG : Successfully read the textblock using UTF-8.

**Comment by GeorgeCiesinski** [comment] 2020-02-28 00:18
Hello, thanks for bringing this bug to my attention. Sorry about the logging being insufficient. I tried to anticipate most of the bugs that would come up in the program, but some are coming up in unexpected places where my exception handling is not capturing them, and therefore, not invoking logging to log those exceptions. I am addressing this issue in my next update to better capture these exceptions and prevent the crash.

The log you posted seems to indicate an error that occurs as the textblocks are opened and decoded. I believe that your textblock file has been automatically saved with the ANSI encoding, or another unsupported encoding. At this time, Text-Script only supports unicode (UTF-16 or UTF-8) as I am still working out a way to reliably decode ANSI. Despite the log saying it decoded using UTF-8, I believe that it misidentified the encoding as some characters can be ambiguous. This information is unfortunately missing from my README so I will be releasing an update to include this. 

As a temporary fix, could you please try opening the textblock file that crashes text-script with notepad, clicking save-as, and select the encoding "unicode". Click save and overwrite the old file. If Text-Script stops crashing, then the issue was the encoding and changing the encoding on the remaining files to Unicode should resolve this. Please let me know if this does not resolve the issue.

**Comment by cgarrett** [comment] 2020-03-02 15:37
It looks like the workaround took care of the issue. I tested all 8 of the textblocks I set up and they all run without crashing the app now.

Thanks!

**Comment by GeorgeCiesinski** [comment] 2020-03-02 19:39
Awesome, thanks for the update and for confirming the cause of the crash. I have resolved this in commit [https://github.com/GeorgeCiesinski/text-script/issues/37](https://github.com/GeorgeCiesinski/text-script/issues/37) which will be pushed hopefully before the end of the week, so I'm closing this case.

**Closed as completed by GeorgeCiesinski** 2020-03-02 19:39 UTC
Labels: bug
